### PR TITLE
Mobile

### PR DESCRIPTION
**Pull request by mukkachaitanya**
Merge this ! Conflict is from your side not mine.

### CODE REVIEW

**Comment by SebastinSanty** [comment]
Wut?

**Comment by SebastinSanty** [comment]
There can't be conflict from my side.

**Comment by mukkachaitanya** [comment]
Even though it shows no conflicts ! 

```
C:\Users\mukka\Documents\Prgm\Waves2k16\Waves-Website\waves\src>git pull --rebase origin master
From https://github.com/SebastinSanty/WavesWebsite2016
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Local Environment Settings changed (Issue #9)
Applying: README Updated
Applying: FrontEnd changes
Applying: Mobile site and Updates
```

**Comment by SebastinSanty** [comment]
How come you are having 4 commits?

**Comment by mukkachaitanya** [comment]
And a totally different commit history on my PC.

```
commit e695b0f070ffb570f69cd3a64bbbdcace72a6785
Author: mukkachaitanya <chaitanya.mvs2007@gmail.com>
Date:   Tue Oct 4 16:35:41 2016 +0530

    Mobile site and Updates

commit 8737dc05e583bb9f4a85af7ce0e39565b89419ba
Author: mukkachaitanya <chaitanya.mvs2007@gmail.com>
Date:   Mon Sep 26 13:30:10 2016 +0530

    FrontEnd changes


commit 3186d3b52c7ef29317b6b5d81c07e1ab3f42e660
Author: Sebastin Santy <sebastinssanty@gmail.com>
Date:   Mon Sep 26 22:21:45 2016 +0530

    README Updated

commit af3ac6c5971943bf1070321e85a36836b2e489d2
Author: Sebastin Santy <sebastinssanty@gmail.com>
Date:   Mon Sep 26 19:09:14 2016 +0530

    Local Environment Settings changed (Issue #9)
```

**Comment by mukkachaitanya** [comment]
FrontEnd changes are from the earlier PR #14 . I didn't squash them to keep originality.

**Pull request closed without merging**
