### PR TITLE
Replace Hospitality tab with Corona

### PR DESCRIPTION
**Pull request by coditva**
## Issues:

1 Hover doesn't change the color of the Corona (beer mugs) icon.
2 The url shows the page to be `/hospitality` and not `/corona`

### CODE REVIEW

**Comment by mukkachaitanya** [comment]
Is it ok to commit the `db.sqlite3` too ?

**Comment by SebastinSanty** [comment]
Yeah its fine, but not recommended. Actually I should remove it from the repo itself.

**Comment by mukkachaitanya** [comment]
I always try not to commit it.

**Comment by SebastinSanty** [comment]
@UtkarshMe : Submit PR from branches, to avoid headaches in future :)

**Pull request merged**
