### PR TITLE
Addressed Issues (#19 and #30)

### PR DESCRIPTION
**Pull request by mukkachaitanya**
## Changelog
- Added countdown timer
- Modified Registration page.

Will be adding further changes soon.

### CODE REVIEW

**Comment by SebastinSanty** [comment]
Can you also address the issue #31. Or else, comment the code out. Rest all is good.

**Comment by mukkachaitanya** [comment]
Added dates.

**Review by SebastinSanty — APPROVED** [review]

**Comment by SebastinSanty** [comment]
Issue #30 is resolved.

**Comment by SebastinSanty** [comment]
Issue #19 is also resolved

**Pull request merged**
